In [5]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [6]:
df=load_iris()
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
X=df.data

In [10]:
y=df.target


In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
from sklearn.model_selection import train_test_split,GridSearchCV

In [14]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [40]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier

In [41]:
ada_clf=AdaBoostClassifier(n_estimators=50,learning_rate=0.5,random_state=42)

In [42]:
ada_clf.fit(x_train,y_train)

C:\Users\cipl\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(learning_rate=0.5, random_state=42)

In [43]:
y_pred_train1=ada_clf.predict(x_train)
y_pred_test1=ada_clf.predict(x_test)

In [95]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [44]:
print('training accuracy',accuracy_score(y_train,y_pred_train1))
print('testing accuracy',accuracy_score(y_test,y_pred_test1))

training accuracy 0.9047619047619048
testing accuracy 0.9777777777777777


# Hyperparameter tuning on Adaboost

In [45]:
param_grid={'n_estimators':[50,100,150],
'learning_rate':[0.01,0.1,0.5,1],}
 


    


In [46]:
grid_search=GridSearchCV(estimator=ada_clf,param_grid=param_grid,cv=5,scoring='accuracy',n_jobs=-1)

In [70]:
import time

In [47]:
start=time.time()
grid_search.fit(x_train,y_train)
end=time.time()
print(end-start)

C:\Users\cipl\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


13.452935934066772


In [48]:
best_paramters=grid_search.best_params_
best_paramters

{'learning_rate': 1, 'n_estimators': 100}

In [49]:
ada_clf1=AdaBoostClassifier(**best_paramters)

In [50]:
ada_clf1.fit(x_train,y_train)

C:\Users\cipl\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(learning_rate=1, n_estimators=100)

In [51]:
Y_pred_train1=ada_clf1.predict(x_train)
Y_pred_test1=ada_clf1.predict(x_test)

In [52]:
print('training accuracy',accuracy_score(y_train,Y_pred_train1))
print('testing accuracy',accuracy_score(y_test,Y_pred_test1))

training accuracy 0.9619047619047619
testing accuracy 1.0


In [21]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

# GradientBoosting

In [22]:
gb_clf=GradientBoostingClassifier()
gb_clf.fit(x_train,y_train)

GradientBoostingClassifier()

In [23]:
y_pred_train2=gb_clf.predict(x_train)
y_pred_test2=gb_clf.predict(x_test)

In [24]:
print('training accuracy',accuracy_score(y_train,y_pred_train2))
print('testing accuracy',accuracy_score(y_test,y_pred_test2))

training accuracy 1.0
testing accuracy 1.0


In [97]:
confusion_matrix(y_train,y_pred_train2)

array([[31,  0,  0],
       [ 0, 37,  0],
       [ 0,  0, 37]], dtype=int64)

In [99]:
confusion_matrix(y_test,y_pred_test2)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

# Hyperparamters tuning on GradienrBoosting

In [29]:
param_grid={'n_estimators':[50,100,150],
'learning_rate':[0.01,0.1,0.5],
'max_depth':[3,5,7],
'subsample':[0.8,1.0]}
 


    


In [30]:
grid_search=GridSearchCV(estimator=gb_clf,param_grid=param_grid,cv=5,scoring='accuracy',n_jobs=-1)

In [31]:
import time

In [32]:
start=time.time()
grid_search.fit(x_train,y_train)
end=time.time()
print(end-start)

104.77346611022949


In [33]:
best_paramters=grid_search.best_params_
best_paramters

{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100, 'subsample': 1.0}

In [35]:
gb_clf1=GradientBoostingClassifier(**best_paramters)


In [36]:
gb_clf1.fit(x_train,y_train)

GradientBoostingClassifier(max_depth=5)

In [37]:
Y_pred_train2=gb_clf.predict(x_train)
Y_pred_test2=gb_clf.predict(x_test)

In [38]:
print('training accuracy',accuracy_score(y_train,Y_pred_train2))
print('testing accuracy',accuracy_score(y_test,Y_pred_test2))

training accuracy 1.0
testing accuracy 1.0


In [108]:
74.80459499359131/60

1.2467432498931885